ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER MotoRent IDENTIFIED BY duoc
--DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER MotoRent QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO MotoRent;
GRANT "CONNECT" TO MotoRent;
ALTER USER MotoRent DEFAULT ROLE "RESOURCE","CONNECT";