ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER MotoRentCL IDENTIFIED BY duoc
--DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER MotoRentCL QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO MotoRentCL;
GRANT "CONNECT" TO MotoRentCL;
ALTER USER MotoRentCL DEFAULT ROLE "RESOURCE","CONNECT";


BEGIN
  FOR t IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/