services:
  - type: web
    name: motorentcl-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "echo 'Iniciando migración...' >> salida.txt && python manage.py migrate >> salida.txt 2>&1 && echo 'Migraciones completas' >> salida.txt && gunicorn MotoRentCL.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db_motorentcl

databases:
  - name: db_motorentcl 