services:
  - type: web
    name: motorentcl-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py createsuperuser --noinput &&
      gunicorn MotoRentCL.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db_motorentcl

databases:
  - name: db_motorentcl 