services:
  - type: web
    name: motorentcl-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "echo '⛏ Ejecutando migrate...' && python manage.py migrate && echo '✅ Migraciones listas' && gunicorn MotoRentCL.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db_motorentcl

databases:
  - name: db_motorentcl 