services:
  - type: web
    name: db_motorentcl
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn MotoRentCL.wsgi 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db_motorentcl

databases:
  - name: db_motorrentcl 