services:
  - type: web
    name: motorentcl-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn MotoRentCL.wsgi
    envVars:
      - key: RENDER
        value: true
      - key: SECRET_KEY
        value: "@6)9#@f_%*%+7m(6l+@-xr+a+w&mc9mxo8)pbf)3e9@x8bg8u&"
      - key: DATABASE_URL
        fromDatabase:
          name: db_motorentcl
          property: connectionString

databases:
  - name: db_motorentcl