services:
  - type: web
    name: motorentcl-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py migrate &&
      echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@gmail.com', 'admin')" | python manage.py shell &&
      python manage.py collectstatic --noinput &&
      gunicorn MotoRentCL.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db_motorentcl

databases:
  - name: db_motorentcl 