# Generated by Django 5.2 on 2025-05-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('power', models.CharField(blank=True, max_length=100, null=True)),
                ('gearbox', models.CharField(blank=True, max_length=100, null=True)),
                ('cooling', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
