# Generated by Django 5.2 on 2025-05-05 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_usuarioregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=15)),
                ('asunto', models.CharField(choices=[('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('consulta', 'Consulta'), ('otro', 'Otro')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
