# Generated by Django 5.2 on 2025-05-05 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('motocicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.motocicleta')),
            ],
        ),
    ]
